# Generated by Django 2.1.7 on 2019-04-03 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='INTC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_date', models.DateTimeField(verbose_name='date')),
                ('open_price', models.FloatField(default=0.0)),
                ('high_price', models.FloatField(default=0.0)),
                ('low_price', models.FloatField(default=0.0)),
                ('close_price', models.FloatField(default=0.0)),
                ('adj_close_price', models.FloatField(default=0.0)),
                ('volume', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='IXIC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_date', models.DateTimeField(verbose_name='date')),
                ('open_price', models.FloatField(default=0.0)),
                ('high_price', models.FloatField(default=0.0)),
                ('low_price', models.FloatField(default=0.0)),
                ('close_price', models.FloatField(default=0.0)),
                ('adj_close_price', models.FloatField(default=0.0)),
                ('volume', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='MSFT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_date', models.DateTimeField(verbose_name='date')),
                ('open_price', models.FloatField(default=0.0)),
                ('high_price', models.FloatField(default=0.0)),
                ('low_price', models.FloatField(default=0.0)),
                ('close_price', models.FloatField(default=0.0)),
                ('adj_close_price', models.FloatField(default=0.0)),
                ('volume', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='NVDA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_date', models.DateTimeField(verbose_name='date')),
                ('open_price', models.FloatField(default=0.0)),
                ('high_price', models.FloatField(default=0.0)),
                ('low_price', models.FloatField(default=0.0)),
                ('close_price', models.FloatField(default=0.0)),
                ('adj_close_price', models.FloatField(default=0.0)),
                ('volume', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='QCOM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_date', models.DateTimeField(verbose_name='date')),
                ('open_price', models.FloatField(default=0.0)),
                ('high_price', models.FloatField(default=0.0)),
                ('low_price', models.FloatField(default=0.0)),
                ('close_price', models.FloatField(default=0.0)),
                ('adj_close_price', models.FloatField(default=0.0)),
                ('volume', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='TSLA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_date', models.DateTimeField(verbose_name='date')),
                ('open_price', models.FloatField(default=0.0)),
                ('high_price', models.FloatField(default=0.0)),
                ('low_price', models.FloatField(default=0.0)),
                ('close_price', models.FloatField(default=0.0)),
                ('adj_close_price', models.FloatField(default=0.0)),
                ('volume', models.FloatField(default=0.0)),
            ],
        ),
    ]
