# Generated by Django 2.1.7 on 2019-04-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intc',
            name='price_date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='ixic',
            name='price_date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='msft',
            name='price_date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='nvda',
            name='price_date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='qcom',
            name='price_date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='tsla',
            name='price_date',
            field=models.DateField(verbose_name='date'),
        ),
    ]
