# Generated by Django 2.1.7 on 2019-04-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20190403_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSCO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_date', models.DateField(verbose_name='date')),
                ('open_price', models.FloatField(default=0.0)),
                ('high_price', models.FloatField(default=0.0)),
                ('low_price', models.FloatField(default=0.0)),
                ('close_price', models.FloatField(default=0.0)),
                ('adj_close_price', models.FloatField(default=0.0)),
                ('volume', models.FloatField(default=0.0)),
            ],
        ),
    ]
